name: nawiapp
description: "Una herramienta pedagógica digital para docentes de inicial"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_floating_buttons: ^0.0.2
  intl: ^0.20.2
  rounded_loading_button_plus: ^3.0.1
  multi_dropdown: ^3.0.1
  manual_speech_to_text: ^1.0.0
  group_list_view: ^1.1.1
  collection: ^1.19.0
  permission_handler: ^11.3.1
  avatar_glow: ^3.0.1
  linkfy_text: ^1.1.6
  mention_tag_text_field: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700